name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        uses: 
          actions/checkout@v2
      - 
        name: 
          docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    
      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: data_governance_testing
          push: true
          tags: $DOCKER_USER/mlops_course:hw_2_github
        

