name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run: 
    runs-on: [ ubuntu-latest ]
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container
        run: |
          docker build -f data_governance_testing/Dockerfile \ 
          --progress=plain --tag=mlops_course:hw-3 . \
          --build-arg GDRIVE_SECRETS_ARG=${{ secrets.GDRIVE_SECRETS }}
      - name: Print Metrics
          echo "## Metrics result" > report.md
          docker run mlops_course:hw-3 cat data_governance_testing/metrics.txt >> report.md
