name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run: 
    runs-on: [ ubuntu-latest ]
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cml
        uses: iterative/setup-cml@v1
      - name: Build container
        run: |
          cd data_governance_testing/
          docker build --progress=plain --tag=mlops_course:hw-3 \
          --build-arg GDRIVE_SECRETS_ARG=${{ secrets.GDRIVE_SECRETS }} .
      - name: Print Metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run mlops_course:hw-3 cat metrics.txt >> metrics.txt
          echo "## Metrics result" > report.md
          cml-publish metrics.txt --md >> report.md
          cml-send-comment --update report.md 
