name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run: 
    runs-on: [ ubuntu-latest ]
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install cml
        uses: iterative/setup-cml@v1
      
      - name: Build container
        run: |
          docker build --file=./docker/Dockerfile --progress=plain --tag=mlops_course:hw-3 \
          --build-arg GDRIVE_SECRETS_ARG=${{ secrets.GDRIVE_SECRETS }} .
      
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docker
          docker-compose run main docker/load_data.sh --verbose
          
          cd ..
          cd ./data_governance_testing
          

          echo "## Metrics result" > report.md          
          dvc metrics diff --show-md master >> report.md
          cat ./outputs/metrics.json >> report.md

          echo "## Plot result" >> report.md
          cml-publish ./outputs/feature_importance.png >> report.md
          
          cml-send-comment --update report.md 
